dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKE
  local_dir: dist/ar-test
  on:
    branch: master